version: "3.8"

services:
    php-fpm:
        # Для установки нужных пакетов используем не чистый образ, а инструкции из конкретного файла Dockerfile
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        container_name: vat-php
        working_dir: /var/www
        volumes:
            - .:/var/www # Монтируем локальную папку в контейнер как /var/www
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    nginx:
        image: nginx:latest
        restart: unless-stopped
        tty: true
        ports:
            - "80:80" # Внутренний порт контейнера пробрасываем на host машину
            - "443:443"
        links:
            - php-fpm
            # - node
        depends_on:
            - php-fpm
        container_name: vat-nginx
        volumes:
            - .:/var/www # Монтируем локальную папку в контейнер как /var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/ # Передаем в контейнер конфигурационные файлы nginx
    db:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=laravel"
        ports:
            - "3306:3306"
        container_name: vat-db
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8085:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        container_name: vat-admin
    node:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www
        working_dir: /var/www
        tty: true
        container_name: vat-node
# Тома
volumes:
    # Чтобы данные БД не пропадали после выключения создаем именованный том
    dbdata:
        driver: local
