export enum InvoiceAlowedActions {
    SIGN_INVOICE = "SIGN_INVOICE",
    CANCEL_INVOICE = "CANCEL_INVOICE",
    EDIT_INVOICE = "EDIT_INVOICE",
    PREVIEW_INVOICE = "PREVIEW_INVOICE",
    PREVIEW_INCOME_INVOICE = "PREVIEW_INCOME_INVOICE",
    COPY_INVOICE = "COPY_INVOICE",
    CONFIRM_CANCELLATION = "CONFIRM_CANCELLATION",
}
