export enum ConfirmPasswordStatus {
    CONFIRMATION_SUCCESS = "CONFIRMATION_SUCCESS",
    CONFIRMATION_FAILED = "CONFIRMATION_FAILED",
    CONFIRMATION_PENDING = "CONFIRMATION_PENDING",
    CONFIRMATION_NOT_ASKED = "CONFIRMATION_NOT_ASKED",
}
